name: ggi_chat
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  diffutil_dart: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.4.3
  flutter_link_previewer: ^3.0.1
  flutter_parsed_text: ^2.2.1
  intl: ^0.17.0
  meta: ^1.7.0
  photo_view: ^0.14.0
  url_launcher: ^6.1.4
  visibility_detector: ^0.3.3
  file_picker: ^4.5.1
  image_picker: ^0.8.5+3
  mime: ^1.0.1
  open_file: ^3.2.1
  uuid: ^3.0.6
  path_provider: ^2.0.11
  socket_io_client: ^2.0.0
  overlay_support: ^2.0.1
  flutter_file_view: ^2.0.5
  pull_to_refresh: ^2.0.0
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.2
  emoji_picker_flutter: 1.3.0
  permission:
    git:
      url: https://github.com/leovu/permission.git
      ref: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.ggi_chat
        pluginClass: GgiChatPlugin
      ios:
        pluginClass: GgiChatPlugin
      web:
        pluginClass: GgiChatWeb
        fileName: ggi_chat_web.dart

  assets:
    - assets/meme/panda/
    - assets/meme/usagyuun/
    - assets/meme/mimicat/
    - assets/icon-rabbit.png
    - assets/icon-emoji.png
    - assets/icon-panda.png
    - assets/icon-cat.png
    - assets/icon-attachment.png
    - assets/icon-delivered.png
    - assets/icon-document.png
    - assets/icon-error.png
    - assets/icon-seen.png
    - assets/icon-send.png
    - assets/2.0x/icon-attachment.png
    - assets/2.0x/icon-delivered.png
    - assets/2.0x/icon-document.png
    - assets/2.0x/icon-error.png
    - assets/2.0x/icon-seen.png
    - assets/2.0x/icon-send.png
    - assets/3.0x/icon-attachment.png
    - assets/3.0x/icon-delivered.png
    - assets/3.0x/icon-document.png
    - assets/3.0x/icon-error.png
    - assets/3.0x/icon-seen.png
    - assets/3.0x/icon-send.png
